#!/usr/bin/env bash

# configure
transArgNoAnsi="-no-ansi" 

if [[ $version -lt 1 ]]; then
    DeprecatedMessage="Calling rofi_verbose directly is not recommend in the new version, consider \"rofi_trans verbose\""
    # A hacky way to solve the version problem :3
    printf "$DeprecatedMessage\n"
    exec rofi_trans verbose
else
    input="$(rofi -dmenu -p translate -lines 0)"
fi

while [[ -n $input ]]; do
    result="$(trans --target=$transTarget $transArgNoAnsi "$input")"
    input="$(rofi -p translate -dmenu -mesg "$result" -lines 0)"
done

