#!/usr/bin/env bash

touch $transHistory

transText=$@
echo ok >> /dev/stderr
echo $transText >> /dev/stderr

function translate {
    trans --target=$transTarget $transArgs "$1"
}

function main {

    if [[ -n $transText ]]; then
        if [[ ! $transText == '#'* ]]; then
            # translate input 
            transResult="$(translate "$transText")"
            printf "#\t%-40s\t%s\n" "$transText" "$transResult" >> $transHistory
        else
            # speak it again
            translate "$(echo "$transText" | cut -f2)" >> /dev/null
        fi
        echo "google" > /tmp/rofi_default
    fi

    tac $transHistory
}

main
