#!/usr/bin/env bash

touch $transHistory

transText=$@

if [[ "$verbose" == "1" ]]; then
    echo ok >> /dev/stderr
    echo $transText >> /dev/stderr
fi

function translate {
    if [[ $verbose ]]; then set -x; fi
    trans --target=$transTarget -e $primary_translator $transArgs "$1"
    if [[ $verbose ]]; then set +x; fi
}

function main {

    if [[ -n $transText ]]; then
        if [[ ! $transText == '#'* ]]; then
            # translate input 
            transResult="$(translate "$transText")"

            # If the translation result is empty, that might means the translator is not available at this moment.
            # Switch to secondary transltor and do that again
            if [[ -z "$transResult" ]]; then
                primary_translator=$secondary_translator 
                transResult="$(translate "$transText")"
            fi

            printf "#\t%-40s\t%s\n" "$transText" "$transResult" >> $transHistory
        else
            # speak it again
            translate "$(echo "$transText" | cut -f2)" >> /dev/null
        fi
    fi

    tac $transHistory
}

main
