#!/usr/bin/env bash

# configure
transHistory="$HOME/.rofi_trans"
transTarget="zh-TW"
transArg=" -b -speak -e bing"

touch $transHistory

transText=$@
echo ok >> /dev/stderr
echo $transText >> /dev/stderr

function translate {
    trans --target=$transTarget $transArg "$1"
}

function main {

    if [[ -n $transText ]]; then
        if [[ ! $transText == '#'* ]]; then
            # translate input 
            transResult="$(translate "$transText")"
            printf "#\t%-40s\t%s\n" "$transText" "$transResult" >> $transHistory
        else
            # speak it again
            translate "$(echo "$transText" | cut -f2)" >> /dev/null
        fi
        echo "bing" > /tmp/rofi_default
    fi

    tac $transHistory
}

main
