#!/usr/bin/env bash

# configure
pattern="$@"

touch $transHistory

# delete pattern
if [[ -n $pattern ]]; then

    # pattern escaping
    pattern="$(echo "$pattern" | sed -e 's/[]\/$*.^[]/\\&/g' )"

    # remove entry by specified pattern
    his="$(cat $transHistory)"
    echo "$his" | sed "/^${pattern}$/d" > $transHistory
fi

# print history
tac $transHistory
