#!/usr/bin/env bash

# TODO: Fix search problem

# This is the entry of rofi trans-shell
# This script require trans-shell itself, if you don't have one.
# You can install it from your package manager(if provided) or from source(clone trans-shell from github)

function Configs {
    # The default translator for translate-shell
    export primary_translator="google"
    # The alternative transltor for translate-shell
    export secondary_translator="bing"

    export transHistory="$HOME/.rofi_trans"
    export transTarget="zh-TW"
    export transArgs="-b -speak"
    export verbose="1"
}

# Setup environment variable for configs.
Configs

rofi -sidebar-mode -modi "translator:rofi_trans_google,delete:rofi_trans_delete" -show "translator"
